name: Mirror Sync (Gitea, Codeberg, GitLab)

on:
  push:
    branches: [ main, master ]
  delete:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  mirror_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Codeberg
        run: |
          git push --force --prune https://BSXLABS:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/BSXLABS/PicoStore-Repo.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*

      - name: Sync to Gitea.com
        run: |
          git push --force --prune https://BSXLAbS2025:${{ secrets.GITEA_TOKEN }}@gitea.com/BSXLAbS2025/PicoStore-Repo.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*

      - name: Sync to GitLab
        run: |
          git push --force --prune https://darksoftwarehelp:${{ secrets.GITLAB_TOKEN }}@gitlab.com/darksoftwarehelp/PicoStore-Repo.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
